import fs from 'fs';
import path from 'path';
import { SEED_PLACEHOLDER } from './coach';
import { EVALS_DIR, draftToFiles, isGeneratedConfig, type EvalDraft } from './evals';
import { REPO_ROOT, resolveRepoPath } from './paths';
import { getSkillsDir } from './settings';
import { readSkill } from './skills';

const KEBAB_NAME = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/**
 * Bridge between the Skill Builder and the EDD eval pipeline: generate a
 * starter eval that embeds a skill as loaded context, and keep its prompt
 * file in sync with the skill without ever touching the eval's config
 * (the user's test refinements live there).
 *
 * Reads through the skills sandbox (lib/skills.ts), writes through the eval
 * sandbox (lib/paths.ts) — this module only owns the mapping between them.
 */

export type SkillEvalStatus = 'none' | 'current' | 'stale' | 'conflict';

export interface SkillEvalInfo {
  status: SkillEvalStatus;
  configPath: string; // repo-relative (whether or not it exists yet)
}

function evalPaths(skillName: string) {
  return {
    configRel: `${EVALS_DIR}/skill-${skillName}.config.yaml`,
    promptRel: `${EVALS_DIR}/skill-${skillName}.prompt.md`,
  };
}

function buildPromptText(skillName: string, description: string, body: string): string {
  return `You have the following skill loaded. Apply its guidance when answering.

<skill name="${skillName}">
${description.trim()}

${body.trim()}
</skill>

Here's the request:
{{request}}
`;
}

export function skillEvalStatus(skillName: string): SkillEvalInfo {
  const { configRel, promptRel } = evalPaths(skillName);
  const configAbs = path.join(REPO_ROOT, configRel);
  if (!fs.existsSync(configAbs)) return { status: 'none', configPath: configRel };
  if (!isGeneratedConfig(configAbs)) return { status: 'conflict', configPath: configRel };

  try {
    const skillsDir = getSkillsDir();
    if (!skillsDir || !KEBAB_NAME.test(skillName)) throw new Error('unreadable');
    const skillMtime = fs.statSync(path.join(skillsDir, skillName, 'SKILL.md')).mtimeMs;
    const promptMtime = fs.statSync(path.join(REPO_ROOT, promptRel)).mtimeMs;
    return { status: skillMtime > promptMtime ? 'stale' : 'current', configPath: configRel };
  } catch {
    // Prompt file missing or skill unreadable — treat as needing a sync.
    return { status: 'stale', configPath: configRel };
  }
}

/** Map of skill name → status for every generated skill eval (one scan, for the list view). */
export function allSkillEvalStatuses(): Record<string, SkillEvalStatus> {
  const evalsDir = path.join(REPO_ROOT, EVALS_DIR);
  if (!fs.existsSync(evalsDir)) return {};
  const out: Record<string, SkillEvalStatus> = {};
  for (const file of fs.readdirSync(evalsDir)) {
    const m = file.match(/^skill-([a-z0-9-]+)\.config\.yaml$/);
    if (!m) continue;
    try {
      out[m[1]] = skillEvalStatus(m[1]).status;
    } catch {
      out[m[1]] = 'conflict';
    }
  }
  return out;
}

export interface SkillEvalResult {
  action: 'created' | 'synced';
  configPath: string;
}

const BASELINE_PROMPT = `Answer the following request.

Here's the request:
{{request}}
`;

/** Create the starter eval (status none) or re-sync the prompt file (status current/stale). */
export function createOrSyncSkillEval(
  skillName: string,
  opts: { ab?: boolean } = {},
): SkillEvalResult {
  const skill = readSkill(skillName); // validates name + existence via the skills sandbox
  const { configRel, promptRel } = evalPaths(skillName);
  const info = skillEvalStatus(skillName);

  if (info.status === 'conflict') {
    throw new Error(
      `${configRel} exists but was not generated by the eval builder — rename or remove it first.`,
    );
  }

  const promptText = buildPromptText(skillName, skill.description, skill.body);

  if (info.status === 'none') {
    const draft: EvalDraft = {
      name: `Skill: ${skillName}`,
      prompt: promptText,
      ...(opts.ab
        ? {
            promptB: BASELINE_PROMPT,
            promptBPath: `${EVALS_DIR}/skill-${skillName}.baseline.prompt.md`,
          }
        : {}),
      models: [{ runner: 'devin', kind: 'cli', model: 'SWE-1.6', enabled: true }],
      judge: 'devin',
      tests: [
        {
          description: 'Starter test — replace with a realistic scenario',
          request: SEED_PLACEHOLDER,
          checks: [
            {
              kind: 'rubric',
              criterion: `The response follows the ${skillName} skill's guidance`,
              metric: 'follows-skill',
              threshold: 0.7,
              weight: 1,
            },
            ...(opts.ab
              ? [
                  {
                    kind: 'ab-winner' as const,
                    criterion: `Which response better follows the ${skillName} skill's guidance?`,
                  },
                ]
              : []),
          ],
        },
      ],
    };
    const files = draftToFiles(draft);
    if (files.configPath !== configRel) {
      throw new Error(`Unexpected slug: ${files.configPath} != ${configRel}`);
    }
    fs.mkdirSync(path.join(REPO_ROOT, EVALS_DIR), { recursive: true });
    fs.writeFileSync(resolveRepoPath(files.promptPath), files.promptText, 'utf8');
    if (files.promptBPath && files.promptBText !== undefined) {
      fs.writeFileSync(resolveRepoPath(files.promptBPath), files.promptBText, 'utf8');
    }
    fs.writeFileSync(resolveRepoPath(files.configPath), files.configYaml, 'utf8');
    return { action: 'created', configPath: configRel };
  }

  // Sync: rewrite the prompt file ONLY — the config (the user's tests) is never opened.
  fs.writeFileSync(resolveRepoPath(promptRel), promptText, 'utf8');
  return { action: 'synced', configPath: configRel };
}
